2025-10-15 08:01:19,076 -INFO- CHECKING INFO
2025-10-15 08:01:19,076 -ERROR-Exception occured
Traceback (most recent call last):
  File "/Users/shashankshekar/Desktop/pythontraining/i27/advance/exceptionhandling/pc11.py", line 7, in <module>
    x =1/0
       ~^~
ZeroDivisionError: division by zero
